/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Business.Business;
import model.Supplier.SupplierDirectory;

/**
 *
 * @author HARSH
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private JPanel ManageCustomersPanel;
    private JPanel ManageSuppliersPanel;
    private SupplierDirectory supplierDirectory;
    Business business;

    /**
     * Creates new form AdminWorkAreaPanel
     */
    public AdminWorkAreaPanel(JPanel userProcessContainer,Business business) {
        initComponents();
        this.business= business;
         this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminWorkSpace = new javax.swing.JLabel();
        btnMngCustomers = new javax.swing.JButton();
        btnMngSupplier = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 51));
        setPreferredSize(new java.awt.Dimension(866, 605));

        lblAdminWorkSpace.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdminWorkSpace.setText("Admin Work Space");

        btnMngCustomers.setText("Manage Customers");
        btnMngCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngCustomersActionPerformed(evt);
            }
        });

        btnMngSupplier.setText("Manage Supplier");
        btnMngSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnMngSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMngCustomers)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(lblAdminWorkSpace)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(lblAdminWorkSpace)
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMngSupplier)
                    .addComponent(btnMngCustomers))
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngSupplierActionPerformed
        // TODO add your handling code here:
        SupplierDirectory supplierDirectory = business.getSupplierDirectory();
    
    if (supplierDirectory == null) {
        JOptionPane.showMessageDialog(this, "Supplier Directory is not available!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Create and navigate to the ManageSuppliersPanel
    ManageSuppliersPanel panel = new ManageSuppliersPanel(userProcessContainer, supplierDirectory);
    userProcessContainer.add("ManageSuppliersPanel", panel);

    // Update layout to show the new panel
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    
    System.out.println("Navigated to ManageSuppliersPanel successfully.");

        
        
        
    }//GEN-LAST:event_btnMngSupplierActionPerformed

    private void btnMngCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngCustomersActionPerformed
       ManageCustomersPanel manageCustomersPanel = new ManageCustomersPanel(userProcessContainer, business);
userProcessContainer.add("ManageCustomersPanel", manageCustomersPanel);
CardLayout layout = (CardLayout) userProcessContainer.getLayout();
layout.next(userProcessContainer);
System.out.println("Business not nukll in mngcust");

        
    }//GEN-LAST:event_btnMngCustomersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngCustomers;
    private javax.swing.JButton btnMngSupplier;
    private javax.swing.JLabel lblAdminWorkSpace;
    // End of variables declaration//GEN-END:variables
}
